class ProductModel {
  final String id;
  final String name;
  final String description;
  final double price;
  final String imagePath;
  final double rating;
  final int reviews;
  final bool isBestDeal;
  final String category;

  ProductModel({
    required this.id,
    required this.name,
    required this.description,
    required this.price,
    required this.imagePath,
    required this.rating,
    required this.reviews,
    this.isBestDeal = false,
    required this.category,
  });

  // Helper method to format price
  String get formattedPrice => 'LKR ${price.toStringAsFixed(0)}/-';
}

// Sample product data using your local assets
final List<ProductModel> sampleProducts = [
  ProductModel(
    id: 'p1',
    name: 'Helapiyasa T-Shirt',
    description: 'Fashion T-shirt for Boys',
    price: 899,
    imagePath: 'assets/product/fashion_01.png',
    rating: 4.0,
    reviews: 125,
    category: 'Fashion',
    isBestDeal: true,
  ),
  ProductModel(
    id: 'p2',
    name: 'Bluetooth Speaker',
    description: 'Wireless Bluetooth Speaker',
    price: 11899,
    imagePath: 'assets/product/electronic_01.png',
    rating: 4.2,
    reviews: 89,
    category: 'Electronics',
  ),
  ProductModel(
    id: 'p3',
    name: 'Chilli Powder',
    description: 'Premium chilli powder for kitchen',
    price: 490,
    imagePath: 'assets/product/family_pack1.png',
    rating: 4.5,
    reviews: 203,
    category: 'Food',
    isBestDeal: true,
  ),
  ProductModel(
    id: 'p4',
    name: 'Coconut Oil',
    description: 'Pure coconut oil from helapiyasa',
    price: 1899,
    imagePath: 'assets/product/oil_01.png',
    rating: 4.3,
    reviews: 156,
    category: 'Food',
  ),
  ProductModel(
    id: 'p5',
    name: 'Beauty Cream',
    description: 'Premium cosmetic cream',
    price: 2499,
    imagePath: 'assets/product/cosmatic_01.png',
    rating: 4.8,
    reviews: 92,
    category: 'Cosmetics',
    isBestDeal: true,
  ),
  ProductModel(
    id: 'p6',
    name: 'Gaming Headset',
    description: 'High quality gaming headset',
    price: 8999,
    imagePath: 'assets/product/electronic_02.png',
    rating: 4.1,
    reviews: 67,
    category: 'Electronics',
  ),
  ProductModel(
    id: 'p7',
    name: 'Ladies Top',
    description: 'Trendy fashion top for women',
    price: 1299,
    imagePath: 'assets/product/fashion_02.png',
    rating: 4.4,
    reviews: 134,
    category: 'Fashion',
  ),
  ProductModel(
    id: 'p8',
    name: 'Cooking Oil',
    description: 'Healthy cooking oil',
    price: 1599,
    imagePath: 'assets/product/oil_02.png',
    rating: 4.0,
    reviews: 178,
    category: 'Food',
  ),
  ProductModel(
    id: 'p9',
    name: 'Face Cream',
    description: 'Anti-aging face cream',
    price: 3299,
    imagePath: 'assets/product/cosmatic_02.png',
    rating: 4.6,
    reviews: 84,
    category: 'Cosmetics',
  ),
  ProductModel(
    id: 'p10',
    name: 'Smart Phone',
    description: 'Latest smart watch technology',
    price: 15999,
    imagePath: 'assets/product/electronic_03.png',
    rating: 4.7,
    reviews: 45,
    category: 'Electronics',
    isBestDeal: false,
  ),
  ProductModel(
    id: 'p11',
    name: 'Helapiyasa T-Shirt',
    description: 'Fashion T-shirt for Boys',
    price: 899,
    imagePath: 'assets/product/fashion_01.png',
    rating: 4.0,
    reviews: 125,
    category: 'Fashion',
    isBestDeal: true,
  ),
  ProductModel(
    id: 'p12',
    name: 'Bluetooth Speaker',
    description: 'Wireless Bluetooth Speaker',
    price: 11899,
    imagePath: 'assets/product/electronic_01.png',
    rating: 4.2,
    reviews: 89,
    category: 'Electronics',
  ),
  ProductModel(
    id: 'p13',
    name: 'Chilli Powder',
    description: 'Premium chilli powder for kitchen',
    price: 490,
    imagePath: 'assets/product/family_pack1.png',
    rating: 4.5,
    reviews: 203,
    category: 'Food',
    isBestDeal: true,
  ),
  ProductModel(
    id: 'p14',
    name: 'Coconut Oil',
    description: 'Pure coconut oil from helapiyasa',
    price: 1899,
    imagePath: 'assets/product/oil_01.png',
    rating: 4.3,
    reviews: 156,
    category: 'Food',
  ),
  ProductModel(
    id: 'p15',
    name: 'Beauty Cream',
    description: 'Premium cosmetic cream',
    price: 2499,
    imagePath: 'assets/product/cosmatic_01.png',
    rating: 4.8,
    reviews: 92,
    category: 'Cosmetics',
    isBestDeal: true,
  ),
  ProductModel(
    id: 'p16',
    name: 'Bluetooth Speaker',
    description: 'High quality JBL Sound',
    price: 8999,
    imagePath: 'assets/product/electronic_02.png',
    rating: 4.1,
    reviews: 67,
    category: 'Electronics',
  ),
  ProductModel(
    id: 'p17',
    name: 'Ladies Top',
    description: 'Trendy fashion top for women',
    price: 1299,
    imagePath: 'assets/product/fashion_02.png',
    rating: 4.4,
    reviews: 134,
    category: 'Fashion',
  ),
  ProductModel(
    id: 'p18',
    name: 'Cooking Oil',
    description: 'Healthy cooking oil',
    price: 1599,
    imagePath: 'assets/product/oil_02.png',
    rating: 4.0,
    reviews: 178,
    category: 'Food',
  ),
  ProductModel(
    id: 'p19',
    name: 'Face Cream',
    description: 'Anti-aging face cream',
    price: 3299,
    imagePath: 'assets/product/cosmatic_02.png',
    rating: 4.6,
    reviews: 84,
    category: 'Cosmetics',
  ),
  ProductModel(
    id: 'p20',
    name: 'Smart Phone',
    description: 'Latest smart watch technology',
    price: 15999,
    imagePath: 'assets/product/electronic_03.png',
    rating: 4.7,
    reviews: 45,
    category: 'Electronics',
    isBestDeal: false,
  ),
];
